### ISSUE TITLE
Manually archiving a channel crashes handler

### ISSUE THREAD

**Issue by madshargreave** [BlakeWilliams/Elixir-Slack#47] opened 2016-02-12 09:15 UTC
Hi

The following piece of code will crash with an `{:handler, :badarg}` error message, if you archive a channel using the Slack web/desktop client. It is however difficult to debug due to the very uninformative error

```
defmodule Test.Stream.Connection do
  use Slack

  def handle_connect(slack, state) do
    IO.inspect "Connected as #{slack.me.name}"
    {:ok, state}
  end

  def handle_message(message, slack, state) do
    {:ok, state}
  end
```

Full error message:

```
error] ** Websocket handler Slacker.Slack.Stream.Connection terminating
** for the reason {:handler, :badarg}
** Handler state was %{slack: %{bots: %{"B0JAQGSDU" => %{deleted: false, id: "B0JAQGSDU",
        name: "gdrive"}},
    channels: %{"C0LN67485" => %{created: 1455043602, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LN67485", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_tju5as7vep8"},
      "C0M2X67K7" => %{created: 1455266494, creator: "U0JAQGSCW",
        has_pins: false, id: "C0M2X67K7", is_archived: true, is_channel: true,
        is_general: false, is_member: true, members: ["U0JAQGSCW"],
        name: "z_127_0_0_1_whvidfq"},
      "C0LMVS78U" => %{created: 1455039521, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LMVS78U", is_archived: false, is_channel: true,
        is_general: false, is_member: false, name: "channel_b2cwhcr0pau"},
      "C0LN7R7KQ" => %{created: 1455042306, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LN7R7KQ", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_x09njzebcne"},
      "C0LNRRUJV" => %{created: 1455052874, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNRRUJV", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_qfbmoalvxky"},
      "C0LNP92PK" => %{created: 1455051374, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNP92PK", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_sq9wqkxczgk"},
      "C0LNVDKU2" => %{created: 1455054589, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNVDKU2", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_8iskpzwwcqu"},
      "C0JAQ9STZ" => %{created: 1452664560, creator: "U0JAQGSCW",
        has_pins: false, id: "C0JAQ9STZ", is_archived: false, is_channel: true,
        is_general: true, is_member: true, last_read: "1452664560.745557",
        latest: %{subtype: "channel_join",
          text: "<@U0JAQGSCW|mads> has joined the channel",
          ts: "1452664560.745557", type: "message", user: "U0JAQGSCW"},
        members: ["U0JAQGSCW"], name: "general",
        purpose: %{creator: "", last_set: 0,
          value: "This channel is for team-wide communication and announcements. All team members are in this channel."},
        topic: %{creator: "", last_set: 0,
          value: "Company-wide announcements and work-based matters"},
        unread_count: 0, unread_count_display: 0},
      "C0LGDKCN7" => %{created: 1454866721, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LGDKCN7", is_archived: false, is_channel: true,
        is_general: false, is_member: false, name: "channel_ip3wclr85vq"},
      "C0LHYFW05" => %{created: 1454939628, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LHYFW05", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_4y9ie2wlcba"},
      "C0LN4336F" => %{created: 1455042185, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LN4336F", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_1fedjx0k0ms"},
      "C0LNK2PQA" => %{created: 1455048575, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNK2PQA", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_pph7qh0p_m4"},
      "C0LNS7QGG" => %{created: 1455052345, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNS7QGG", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_t7hy0i8wbq8"},
      "C0M0JCSF9" => %{created: 1455218586, creator: "U0JAQGSCW",
        has_pins: false, id: "C0M0JCSF9", is_archived: false, is_channel: true,
        is_general: false, is_member: false, name: "z_127_0_0_1_vm6rvlw"},
      "C0LNT3S8M" => %{created: 1455055243, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNT3S8M", is_archived: false, is_channel: true,
        is_general: false, is_member: false, name: "channel_d_2nxoggzhm"},
      "C0LNDDS3Y" => %{created: 1455045260, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNDDS3Y", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_70she9wigpu"},
      "C0LJ38YGG" => %{created: 1454939713, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LJ38YGG", is_archived: false, is_channel: true,
        is_general: false, is_member: false, name: "channel_ppuowhm_-9s"},
      "C0LNLQCQ4" => %{created: 1455053120, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNLQCQ4", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_3ysc6n_bcek"},
      "C0M0C4CSG" => %{created: 1455218346, creator: "U0JAQGSCW",
        has_pins: false, id: "C0M0C4CSG", is_archived: false, is_channel: true,
        is_general: false, is_member: true, last_read: "1455266419.000002",
        latest: %{text: "test", ts: "1455266419.000002", type: "message",
          user: "U0JAQGSCW"}, members: ["U0JAQGSCW"],
        name: "z_127_0_0_1_aghtnfs",
        purpose: %{creator: "", last_set: 0, value: ""},
        topic: %{creator: "", last_set: 0, value: ""}, unread_count: 0,
        unread_count_display: 0},
      "C0LNJ4FMF" => %{created: 1455048430, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNJ4FMF", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_pi4mgba6kic"},
      "C0LNQNY6N" => %{created: 1455051836, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNQNY6N", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_5liisfzgbw8"},
      "C0LUFD8GK" => %{created: 1455191024, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LUFD8GK", is_archived: false, is_channel: true,
        is_general: false, is_member: true, last_read: "1455191025.000003",
        latest: %{attachments: [%{fallback: "NO FALLBACK DEFINED",
             fields: [%{short: false, title: "IP Address", value: "127.0.0.1"},
              %{short: false, title: "Browser",
                value: "Chrome (48.0.2564.103)"},
              %{short: false, title: "OS", value: "mac (10.11.2)"}], id: 1,
             mrkdwn_in: ["pretext"], pretext: "*Visitor Information*"}],
          subtype: "bot_message", text: "", ts: "1455191025.000003",
          type: "message", username: "bot"}, members: ["U0JAQGSCW"],
        name: "channel_jk4dklsnrky",
        purpose: %{creator: "", last_set: 0, value: ""},
        topic: %{creator: "", last_set: 0, value: ""}, unread_count: 0,
        unread_count_display: 0},
      "C0LN1KL2V" => %{created: 1455039643, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LN1KL2V", is_archived: false, is_channel: true,
        is_general: false, is_member: false, name: "channel_r_jzzlb61wc"},
      "C0LNUM6DP" => %{created: 1455054504, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNUM6DP", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_bvhkgqj3heq"},
      "C0JAQDJ02" => %{created: 1452664922, creator: "U0JAQGSCW",
        has_pins: false, id: "C0JAQDJ02", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_xb2wifmo2bs"},
      "C0LN3FG3W" => %{created: 1455043548, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LN3FG3W", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_ks351ozkf_a"},
      "C0LNT8HQX" => %{created: 1455053422, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNT8HQX", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_dv8ecrorkye"},
      "C0LNLEEHK" => %{created: 1455051416, creator: "U0JAQGSCW",
        has_pins: false, id: "C0LNLEEHK", is_archived: true, is_channel: true,
        is_general: false, is_member: false, name: "channel_ybckv-rbfou"},
      "C0LS5173L" => %{created: 1455130814, creato (truncated)
```

**Comment by BlakeWilliams** [comment] 2016-02-12 18:11
@christophermaier You were recently working with something similar, any thoughts?

**Comment by christophermaier** [comment] 2016-02-13 00:45
Nothing immediately springs to mind, given a brief look at the code and API docs. I'd probably start by adding some logging statements around [here](https://github.com/BlakeWilliams/Elixir-Slack/blob/d0d497074ab2173bff1ca75d33442ca890f44203/lib/slack/handlers.ex#L48-L50) to get a better picture of what's going on, though.

**Comment by BlakeWilliams** [comment] 2016-04-29 01:22
This might be caused for not having a fallthrough for `handle_message/3`. Try adding `def handle_message(_, _, state), do: {:ok, state}` to your app.

Closing for now since there's not enough information to reproduce a bug.

**Closed by BlakeWilliams** 2016-04-29 01:22 UTC

**Comment by wende** [comment] 2016-05-12 15:43
Same issue here. And as far as I see in this code there's only a fall through handler
