### ISSUE TITLE
Does not actually run in its own process

### ISSUE THREAD

**Issue by FLamparski** [BlakeWilliams/Elixir-Slack#74] opened 2016-07-16 19:32 UTC
The `Slack` RTM client does not run in its own process like a real `GenServer` would. This caused me a lot of confusion when I was trying to add a Supervisor that restarts the Slack client in case of the remote host closing the websocket connection. The PID returned from `Slack.start_link/1` is for the underlying `websocket_client` process.

The `Slack` client should run in its own process and be better at being supervisable. A workaround might be to do something like this:

```elixir
defmodule SlackRtmClient do
  use GenServer

  def start_link(token) do
    {:ok, pid} = GenServer.start_link(__MODULE__, :ok, name: SlackRtmClient.Instance)
    spawn fn -> SlackRtmClientImpl.start_link(token) end
    {:ok, pid}
  end

  def handle_cast({:exit, reason}, _) do
    {:noreply, Process.exit(self(), reason)}
  end

  # rest of GenServer stuff
end

defmodule SlackRtmClientImpl do
  use Slack
  require Logger

  def handle_close(:remote = reason, slack) do
    Logger.warn "Connection closed by remote host"
    GenServer.cast(SlackRtmClient.Instance, {:exit, reason})
  end

  # rest of implementation
end
```

As an aside to aid people debugging: To generate cases where Slack closes the connection on their end, use a test token and force it to be re-issued (you can do it on the [test tokens page](https://api.slack.com/docs/oauth-test-tokens)). This will close all connections opened with that token before giving you a new one.

**Comment by BlakeWilliams** [comment] 2016-07-17 01:17
I'm not really sure what the issue is here, can you explain what you're trying to do and what's breaking?

Is the issue that the websocket connection and the slack handler are coupled?

**Comment by BlakeWilliams** [comment] 2016-07-25 13:02
Closing until there is more detail.

**Closed by BlakeWilliams** 2016-07-25 13:02 UTC

**Comment by bttf** [comment] 2016-08-26 22:16
I think the issue is that `Slack.start_link/1` is not returning its own PID but `websocket_client`'s PID?  So using a Supervisor to start/stop/restart the Slack client rather than `websocket_client` is not possible
