### ISSUE TITLE
Bot goes offline but handle_close is not called

### ISSUE THREAD

**Issue by Lugghawk** [BlakeWilliams/Elixir-Slack#77] opened 2016-08-03 00:00 UTC
Running with `mix run --no-halt` eventually has my bot go offline, and my handle_close is not called.

my handle close is as follows

```
 def handle_close(reason, _slack) do  
    IO.puts "websocket closed"  
    raise reason  
  end
```

And my bot will go offline from slack without this output appearing, and with no error being raised.

**Comment by Lugghawk** [comment] 2016-08-14 22:09
I added some debugging output into the websocket lib. It looks like the last message that I see come out is a `{:ping, ""}` message.

So it's possible that the response isn't being received by slack for some reason, and the socket is terminated without knowing.

**Comment by BlakeWilliams** [comment] 2016-08-15 02:09
Do you have information how to reliably reproduce the issue?

**Comment by Lugghawk** [comment] 2016-08-15 02:26
The bot is here (https://github.com/Lugghawk/slack_pricecheck), but you'll need tokens for slack and ITAD integrations. So without that, the only thing I can think of is having a fairly bare bot that doesn't send any messages (my bot is fairly inactive).

Is there anything I can do to provide you with better logs of the problem?

**Comment by BlakeWilliams** [comment] 2016-08-15 02:28
> the only thing I can think of is having a fairly bare bot that doesn't send any messages (my bot is fairly inactive).

I'll give that a shot and see what happens. There's no built in debugging/logging that would help in the lib currently, unfortunately.

**Comment by Lugghawk** [comment] 2016-08-15 02:35
Yeah that's okay. I've placed a bunch of IO.inspect calls in my local build trying to figure it out. The last one that gets called is in the ping handler, and then the got goes offline and no more logs from anything else.

It also happens after 24+ hours.

**Comment by user5812346** [comment] 2016-08-17 06:35
I have seen this behavior too but often after serveral days of uptime

**Comment by Lugghawk** [comment] 2016-09-12 17:40
Any ideas here? My bot currently needs to be restarted every few days in order to maintain being up. I might get to a point where I'll need to restart the bot process every day, but that seems like a really unfortunate thing to do inside the erlang vm.

**Comment by BlakeWilliams** [comment] 2016-09-12 20:34
What version of the library are you running into this on?

**Comment by sztosz** [comment] 2016-09-23 20:42
I today have some problems with my internet connection and it simply disconnects for few seconds, and ie. my streamed music stops playing.

I run my bot in dev through `iex -S mix`
 
Here's what I observed. When connection dies(music stops playing, and pinging returns me `Destination Net Unreachable`  there is no information in iex log, nor application crash, simply nothing. Messages obviously does not arrive from slack, and bot's not responding.

When connection get's back (my music starts playing, pinging return time in ms) bot applications still does not produce any output. You can send messages but bot does not receive them. 

I think it would be nice if bot could somehow ping slack_server and tried to reconnect if connection was dropped and restored.

I use version `0.7.0`

**Comment by BlakeWilliams** [comment] 2016-09-28 03:01
I've started work on a new branch that should hopefully resolve this issue and several others.

There are a few breaking changes, but I don't think anything too drastic. If anyone has a chance to try it out please leave feedback on wether it works or not (or other comments!).

https://github.com/BlakeWilliams/Elixir-Slack/pull/86

**Comment by nickve28** [comment] 2016-10-08 12:16
Hello,

I tried using the work you made in the new branch, but unfortunately still encountered the same problem.
I did find the potential cause (at least I think/hope so), and was able to recover the slack bot by specifying a keepalive option to the websocket.

So long story short, I added the following to the websocket start_link:
`client.start_link(url, __MODULE__, state, [keepalive: 30000]) #./lib/bot.ex`

By specifying this, and afterwards running the bot in dev (iex -S mix), then shutting off my wifi and reconnect in a few seconds, the bot will stay 'zombie' for a small time period, then it seems ondisconnect gets called with the reason {:error, :keepalive_timeout}.

After this, my supervisor brings the bot up again.

I'm not sure if this is the solution, but at least it seems somewhat related. It seems to solve the problem I've been facing at least.
Hope it helps.

**Comment by BlakeWilliams** [comment] 2016-10-26 00:54
@nickve28 That did help! I managed to track this down today and I think I've got a fix.

In #88 I make a keepalive timeout configurable which was introduced in #86. This is the amount of time the client waits for a response from the server before it closes the connection. I think this should resolve the issue.

**Comment by BlakeWilliams** [comment] 2016-11-11 15:36
Closing since I think this is resolved, feel free to reopen if it's not.

**Closed by BlakeWilliams** 2016-11-11 15:36 UTC
